plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.141'
}

repositories {
    mavenLocal()
    maven { url = 'https://maven.neoforged.net/releases' }
    mavenCentral()
}

version = '1.2.3+26.2-neoforge'
group = 'com.kishku7'
base { archivesName = 'trident-killers-4-java' }

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = '26.2.0-alpha.0+rc-2.20260614.200134'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}